###################################
# INGRESS
###################################
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ing
  namespace: default
spec:
  ingressClassName: external-nginx
  rules:
    - host: "34.171.225.63.nip.io"
      http:
        paths:
          - path: /public
            pathType: Prefix
            backend:
              service:
                name: servicio-public
                port:
                  number: 80
          - pathType: Prefix
            path: /users
            backend:
              service:
                name: servicio-users
                port: 
                  number: 80
