###################################
# INGRESS
###################################
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ing
  namespace: default
  annotations:
    kubernetes.io/ingress.allow-http: "true"
    cert-manager.io/issuer: letsencrypt-prod
    #nginx.ingress.kubernetes.io/auth-skip-uri: "/public/register|/public/login"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/auth-url: "http://servicio-public.default.svc.cluster.local/public/validate"
    nginx.ingress.kubernetes.io/auth-method: POST
    nginx.ingress.kubernetes.io/auth-response-headers: "Authorization, X-User-Roles"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"  # Replace with your web app's origin
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS, PUT, DELETE"  # Allow necessary methods
    nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization, Content-Type"  # Allow necessary headers
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Access-Control-Allow-Origin: '*'";
      more_set_headers "Access-Control-Allow-Methods: GET, POST, OPTIONS";
      more_set_headers "Access-Control-Allow-Headers: authorization";

spec:
  tls:
    - secretName: letsencrypt-prod
  ingressClassName: external-nginx
  rules:
    - host: "34.171.225.63.nip.io"
      http:
        paths:
          - path: /public
            pathType: Prefix
            backend:
              service:
                name: servicio-public
                port:
                  number: 80
          - pathType: Prefix
            path: /users
            backend:
              service:
                name: servicio-users
                port: 
                  number: 80
          - pathType: Prefix
            path: /assignments
            backend:
              service:
                name: servicio-assignments
                port: 
                  number: 80
          - pathType: Prefix
            path: /companies
            backend:
              service:
                name: servicio-companies
                port: 
                  number: 80
          - pathType: Prefix
            path: /interviews
            backend:
              service:
                name: servicio-interviews
                port: 
                  number: 80   
          - pathType: Prefix
            path: /users-get
            backend:
              service:
                name: servicio-users-get
                port: 
                  number: 80
          - pathType: Prefix
            path: /companies-get
            backend:
              service:
                name: servicio-companies-get
                port: 
                  number: 80
          - pathType: Prefix
            path: /assignments-get
            backend:
              service:
                name: servicio-assignments-get
                port: 
                  number: 80
          - pathType: Prefix
            path: /interviews-get
            backend:
              service:
                name: servicio-interviews-get
                port: 
                  number: 80
