# Ejemplo de github action para probar python
# Docs: https://docs.github.com/es/actions/using-workflows/workflow-syntax-for-github-actions
name: CI/CD Pipeline Back

on:
  push:
    branches:
      - main

env: 
  PROJECT_ID: projectid
  CLUSTER_NAME: clustername
  ZONE: zone

jobs:
  build-backend:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [ 3.11 ]
    steps:
      - uses: actions/checkout@v1
      - name: Run tests for public
        working-directory: ./public
        run: |
          pip install pipenv
          pip install httmock
          pipenv sync --system --dev
          export VIRTUAL_ENV="$(pipenv --venv)" PATH="$(pipenv --venv)/bin:$PATH"
          pytest --cov=src -v -s --cov-fail-under=80

      - name: Login to Google Cloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@main
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./public .
          push: true
          tags: gcr.io/${{ secrets.PROJECT_ID }}/public:${{ github.sha }}


