# Ejemplo de github action para probar python
# Docs: https://docs.github.com/es/actions/using-workflows/workflow-syntax-for-github-actions
name: CI/CD Pipeline Back

on:
  push:
    branches:
      - main

env: 
  PROJECT_ID: abc-jobs-miso
  CLUSTER_NAME: primary
  ZONE: us-central1

jobs:
  build-backend:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [ 3.11 ]
    steps:
      - uses: actions/checkout@v1
      - name: Run tests for public
        working-directory: ./public
        run: |
          pip install pipenv
          pip install httmock
          pipenv sync --system --dev
          export VIRTUAL_ENV="$(pipenv --venv)" PATH="$(pipenv --venv)/bin:$PATH"
          pytest --cov=src -v -s --cov-fail-under=80

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'


      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: public
          push: true
          tags: gcr.io/${{ secrets.PROJECT_ID }}/public:1.0

      - name: Login to Google Cloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy to GKE
        run: |
          gcloud config set project $PROJECT_ID
          gcloud config set compute/zone $ZONE
          gcloud container clusters get-credentials $CLUSTER_NAME

      - name: Apply deployment
        run: |
          kubectl apply -f deployment.yaml


